// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: sugar/v1/message.proto

package sugar_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OneofWrapper bool `protobuf:"varint,1,opt,name=oneof_wrapper,json=oneofWrapper,proto3" json:"oneof_wrapper,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sugar_v1_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sugar_v1_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sugar_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetOneofWrapper() bool {
	if x != nil {
		return x.OneofWrapper
	}
	return false
}

var file_sugar_v1_message_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Message)(nil),
		Field:         93563482,
		Name:          "sugar.v1.message",
		Tag:           "bytes,93563482,opt,name=message",
		Filename:      "sugar/v1/message.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional sugar.v1.Message message = 93563482;
	E_Message = &file_sugar_v1_message_proto_extTypes[0]
)

var File_sugar_v1_message_proto protoreflect.FileDescriptor

var file_sugar_v1_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x75, 0x67, 0x61, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x75, 0x67, 0x61, 0x72, 0x2e,
	0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x57, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x3a, 0x4f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xda, 0xd4, 0xce, 0x2c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x75, 0x67, 0x61,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x6e, 0x74, 0x6f, 0x70, 0x73, 0x2f, 0x73, 0x75, 0x67, 0x61,
	0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x67, 0x61, 0x72, 0x5f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sugar_v1_message_proto_rawDescOnce sync.Once
	file_sugar_v1_message_proto_rawDescData = file_sugar_v1_message_proto_rawDesc
)

func file_sugar_v1_message_proto_rawDescGZIP() []byte {
	file_sugar_v1_message_proto_rawDescOnce.Do(func() {
		file_sugar_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_sugar_v1_message_proto_rawDescData)
	})
	return file_sugar_v1_message_proto_rawDescData
}

var file_sugar_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sugar_v1_message_proto_goTypes = []interface{}{
	(*Message)(nil),                     // 0: sugar.v1.Message
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_sugar_v1_message_proto_depIdxs = []int32{
	1, // 0: sugar.v1.message:extendee -> google.protobuf.MessageOptions
	0, // 1: sugar.v1.message:type_name -> sugar.v1.Message
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sugar_v1_message_proto_init() }
func file_sugar_v1_message_proto_init() {
	if File_sugar_v1_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sugar_v1_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sugar_v1_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_sugar_v1_message_proto_goTypes,
		DependencyIndexes: file_sugar_v1_message_proto_depIdxs,
		MessageInfos:      file_sugar_v1_message_proto_msgTypes,
		ExtensionInfos:    file_sugar_v1_message_proto_extTypes,
	}.Build()
	File_sugar_v1_message_proto = out.File
	file_sugar_v1_message_proto_rawDesc = nil
	file_sugar_v1_message_proto_goTypes = nil
	file_sugar_v1_message_proto_depIdxs = nil
}
